/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

import java.awt.Font;

/**
 *
 * @author edina
 */
public class Viewgenio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Viewgenio.class.getName());

    /**
     * Creates new form view
     */
    public Viewgenio() {
        initComponents();
        Frase.setText("<html>Vou pensar em um valor entre <strong>1 e 5</strong>. Tente adivinhar</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Frase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valortxt = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(204, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Frase.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        Frase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Frase.setText("Frase");
        jPanel1.add(Frase, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 200, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/pngwing.com.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 301, -1));

        jLabel4.setFont(new java.awt.Font("Magneto", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Valor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        valortxt.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        valortxt.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        jPanel1.add(valortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 90, -1));

        btnPalpite.setBackground(new java.awt.Color(255, 204, 51));
        btnPalpite.setFont(new java.awt.Font("Magneto", 0, 24)); // NOI18N
        btnPalpite.setForeground(new java.awt.Color(0, 0, 51));
        btnPalpite.setText("Palpite");
        btnPalpite.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));
        btnPalpite.addActionListener(this::btnPalpiteActionPerformed);
        jPanel1.add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 110, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/Adobe Express - file.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        // Gera um número aleatório entre 1 e 5
        double n = 1 + Math.random() * (6 - 1);
        // Converte o número para inteiro
        int valor = (int) n;
        
        // Pega o valor digitado pelo usuário
        int num = Integer.parseInt(valortxt.getValue().toString());
        // Mensagens caso o usuário acerte ou erre
        String f1 = "<html>ACERTOU!</html>";
        String f2 = "<html>ERROU! Eu pensei no valor " +  valor + "</html>";
        
        // Operador ternário: se acertar usa f1, senão usa f2
        String res = (valor == num)?f1:f2;
        
        // Define a fonte do texto
        Frase.setFont(new Font("Arial Black", Font.PLAIN, 16));
        
        // Mostra o resultado
        Frase.setText(res);
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Viewgenio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Frase;
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner valortxt;
    // End of variables declaration//GEN-END:variables
}
