spring.application.name=prg03edinaizemr

spring.main.web-application-type=none
spring.datasource.url=jdbc:postgresql://localhost:5433/curso_db2
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true